### PR TITLE
Add my doom fire effect experiment

### PR DESCRIPTION
**Pull request by NiklasKnaack**
Added a new variation of the Doom fire effect. This experiment introduces a unique approach to the fire animation, enhancing the visual dynamics while keeping it performant in JavaScript. I believe this adds an interesting new style to the collection and complements the existing experiments well.

### CODE REVIEW

**Comment by filipedeschamps** [comment]
This is amazing! Could you also add yourself to the `README` file?

**Comment by NiklasKnaack** [comment]
Hi, many thanks.
You mean the README in the root? ## Experiments and also ## Contributors? Or what do you mean exactly? Thank you!

**Comment by NiklasKnaack** [comment]
Ok. done. Thx!

**Comment by filipedeschamps** [comment]
Merged 🎉

**Pull request merged**
